name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Smoke import
        run: |
          python - <<'PY'
          import importlib
          import sys
          for m in ['langchain', 'langchain_community', 'langchain_groq', 'faiss', 'streamlit']:
              importlib.import_module(m)
          print('OK')
          PY
